### ISSUE TITLE
Has there been a change in format?

### ISSUE THREAD

**Issue by infvie** [OrganicIrradiation/ratebeer#53]
![image](https://user-images.githubusercontent.com/41996797/51951430-96337500-2402-11e9-81ba-9ef04435f53c.png)

**Comment by Oddgod** [comment]
I was going to build this from scratch this weekend. I would be happy to go through and update the whole system for you if you can tell me all the issues? Ideally, if you could give me a task list I'd happily take over.

**Comment by parryc** [comment]
Oh, perfect, @Oddgod. I will clean up my in-progress fork and bring it in to master so you don't have to start from scratch and then create a list of things that I know are still required. Will @ you again when it's ready. Thanks!

**Comment by parryc** [comment]
@Oddgod – I've made a list in #55 of the things that are known, of which @infvie, your issue is one of them. I'm going to close this issue out.

If either of you notice more things that are wrong that you would like to use, or if there are features that this library has not uptaken yet, please comment on #55 so it is all in one place. Thank you!
